title:              Evangelización Ame
email:              aministerioevangelizacion@gmail.com
description:        Somos una comunidad de laicos que a partir del encuentro con Jesús resucitado, Señor y Dios nuestro, tratamos de responder a nuestro compromiso como bautizados a nivel personal y comunitario sirviendo a los demás.
author:             Lucachaco
baseurl:            "/evangelizacioname-dev"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   evangelizacioname
github_username:    evangelizacioname
facebook_username:  evangelizacioname
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
